version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
    reviewers:
      - "rohitkumarnaidu"
      - "saiusesgithub"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "rohitkumarnaidu"
      - "saiusesgithub"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
